apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-ingress
  namespace: strava-logging
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /kibana
        pathType: Prefix
        backend:
          service:
            name: kibana-svc
            port:
              number:
                5601
      - path: /
        pathType: Prefix 
        backend:
          service:
            name: strava-ingest-svc
            port:
              number:
                5000
