version: '3'
services:
  web:
    image: strava_ingest
    ports:
      - 5000:5000
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: httpd.access
    links:
      - fluentd
  fluentd:
    image: fluent/fluentd
    ports:
      - 24224:24224
    volumes:
      - ./fluentd:/fluentd/etc
    environment:
      - FLUENTD_CONF=strava_ingest.conf
    links:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:7.16.2
    ports:
      - 9200:9200
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  kibana:
    image: kibana:7.16.2
    links:
      - elasticsearch
    ports:
      - 5601:5601
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: httpd.access