version: '3'
services:
  web:
    image: strava_ingest
    ports:
      - 5000:5000
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: httpd.access
    links:
      - fluentd
    environment:
      - STRAVA_CLIENT_ID=
      - STRAVA_CLIENT_SECRET=
  fluentd:
    image: fluent/fluentd
    ports:
      - 24224:24224
    volumes:
      - ./fluentd:/fluentd/etc
    environment:
      - FLUENTD_CONF=strava_ingest.conf
